C_Tut/C_Tut/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('accounts/',include('accounts.urls')),
    path('home/',include('home.urls')),
    path('tutorials/',include('tutorials.urls')),
    path('quiz/',include('quizz.urls')),
    path('contact/',include('contact.urls')),
    path('admin/', admin.site.urls),
]

C_Tut/accounts/urls.py
from django.urls import path
from . import views


app_name='accounts'
urlpatterns=[
    path('', views.index , name='index'),
    path( 'login/' , views.loginUser.as_view() , name='login'),
    path('signup',views.signupUser.as_view(),name='signup'),
    path('logout',views.logout_user.as_view(),name='logout'),
]

C_Tut/contact/urls.py
from django.urls import path
from . import views

app_name='contact'
urlpatterns=[
    path('',views.contact,name='contact'),
]

C_Tut/home/urls.py
from django.urls import path
from . import views


app_name='home'
urlpatterns=[
    path('',views.index,name='index'),
    path('about',views.about,name="about"),
    path('team',views.team,name="team"),
]

C_Tut/contact/models.py
from django.db import models

class Contact(models.Model):
    first_name=models.CharField(max_length=50)
    last_name=models.CharField(max_length=50)
    email=models.EmailField()
    message=models.TextField()
    
    def __str__(self):
        return self.first_name+" "+self.last_name

C_Tut/home/models.py
from django.db import models
from django.contrib.auth.models import User


class CPerson(models.Model):
    user=models.OneToOneField(User,on_delete=models.CASCADE)
    types=(
        ('student','student'),
    )
    type=models.CharField(max_length=20,choices=types,default='student')
    
    def __str__(self):
        return self.user.first_name+" "+self.user.last_name
    
class student(models.Model):
    cperson=models.OneToOneField(CPerson,on_delete=models.CASCADE)
    collage_name=models.CharField(max_length=100)
    progress=models.IntegerField(default=1)
    
    def __str__(self):
        return self.cperson.user.first_name+" "+self.cperson.user.last_name

C_Tut/contact/forms.py
from django import forms
from .models import Contact

class contactForm(forms.Form):
    first_name=forms.CharField(max_length=30)
    last_name=forms.CharField(max_length=30)
    email=forms.EmailField(max_length=256)
    message=forms.CharField(widget=forms.Textarea)
    
    class Meta:
        model=Contact
        fields=('first_name','last_name','email','message')

C_Tut/contact/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse, HttpResponseRedirect
from . import forms
from .models import Contact
# Create your views here.
def contact(request):
    temp_name='home/contact.html'
    
    if request.method=="GET":
        form=forms.contactForm()
        context={
            'form':form,
        }
        return render(request,temp_name,context)

    else:
        form=forms.contactForm(request.POST)
        
        if form.is_valid():
            first_name=form.cleaned_data['first_name']
            last_name=form.cleaned_data['last_name']
            email=form.cleaned_data['email'] 
            message=form.cleaned_data['message']
            contact=Contact(first_name=first_name,last_name=last_name,email=email,message=message)
            contact.save()
            form=forms.contactForm()
            message="We will respond Soon...........Thankyou!!!"
            context={
                'message':message,
                'form':form,
            }
            return render(request,temp_name,context)
        
    

C_Tut/home/views.py
from django.shortcuts import render

# Create your views here.
def index(request):
    return render(request,'home/homepage.html')
def about(request):
    return render(request,'home/about.html')
def team(request):
    return render(request,'home/team.html')

C_Tut/home/templates/home/about.html
{% extends '../home/baselayout.html' %}
{% load static %}

{% block content %}
<p>Welcome to about page..</p>
{% endblock %}

C_Tut/home/templates/home/baselayout.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<title>JDPTUTS.com</title>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<link rel="stylesheet" type="text/css" href="{% static 'home/w3.css' %}">
<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Lato">
<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Montserrat">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
<style>
body,h1,h2,h3,h4,h5,h6 {font-family: "Lato", sans-serif}
.w3-bar,h1,button {font-family: "Montserrat", sans-serif}
.fa-anchor,.fa-coffee {font-size:200px}
</style>
<body>

<!-- Navbar -->
<div class="w3-top">
  <div class="w3-bar w3-black w3-card w3-center w3-large">
    <a class="w3-bar-item w3-button w3-hide-medium w3-hide-large w3-right w3-padding-large w3-hover-amber w3-large w3-black" href="javascript:void(0);" onclick="myFunction()" title="Toggle Navigation Menu"><i class="fa fa-bars"></i></a>
      <div style="max-width: 1170px;margin-left: 570px;">
    <a href="{% url 'home:index' %}" class="w3-bar-item w3-button w3-padding-large w3-hover-amber">Home</a>
    <a href="{% url 'home:about' %}" class="w3-bar-item w3-button w3-hide-small w3-padding-large w3-hover-amber">About</a>
    <a href="{% url 'contact:contact' %}" class="w3-bar-item w3-button w3-hide-small w3-padding-large w3-hover-amber">Contact</a>
    <a href="{% url 'home:team' %}" class="w3-bar-item w3-button w3-hide-small w3-padding-large w3-hover-amber">Team</a>
  </div>
</div>

  <!-- Navbar on small screens -->
  <div id="navDemo" class="w3-bar-block w3-white w3-hide w3-hide-large w3-hide-medium w3-large">
    <a href="{% url 'home:index' %}" class="w3-bar-item w3-button w3-padding-large w3-black w3-hover-amber">Home</a>
    <a href="{% url 'home:about' %}" class="w3-bar-item w3-button w3-padding-large w3-black w3-hover-amber">About</a>
    <a href="{% url 'contact:contact' %}" class="w3-bar-item w3-button w3-padding-large w3-black w3-hover-amber">Contact</a>
    <a href="{% url 'home:team' %}" class="w3-bar-item w3-button w3-padding-large w3-black w3-hover-amber">Team</a>
  </div>
</div>

<!-- Header -->
<header class="w3-container w3-black w3-center" style="padding:128px 16px">
  <h1 class="w3-margin w3-jumbo">JDP_TUTS</h1>
  <p class="w3-xlarge" style="font-style: oblique">Most&nbsp;Beginner&nbsp;Friendly&nbsp;Tutorials&nbsp;for&nbsp;Programmers</p>
    <a href="{% url 'accounts:login' %}">
  <button class="w3-btn w3-amber w3-padding-large w3-large w3-margin-top w3-hover-grey">Start Tutorial</button>
    </a>
</header>

    {% block content %}
    {% endblock %}
    
    <div class="w3-container w3-black w3-center w3-opacity w3-padding-64">
    <h1 class="w3-margin w3-xlarge">Quote of the day: live life</h1>
</div>

<!-- Footer -->
<footer class="w3-container w3-padding-64 w3-center w3-opacity">  
  <div class="w3-xlarge w3-padding-32">
    <i class="fa fa-facebook-official w3-hover-opacity"></i>
    <i class="fa fa-instagram w3-hover-opacity"></i>
    <i class="fa fa-snapchat w3-hover-opacity"></i>
    <i class="fa fa-pinterest-p w3-hover-opacity"></i>
    <i class="fa fa-twitter w3-hover-opacity"></i>
    <i class="fa fa-linkedin w3-hover-opacity"></i>
 </div>
 <p>Powered by <a href="{% url 'home:index' %}" target="_blank">JDPTUTS</a></p>
</footer>

<script>
// Used to toggle the menu on small screens when clicking on the menu button
function myFunction() {
  var x = document.getElementById("navDemo");
  if (x.className.indexOf("w3-show") == -1) {
    x.className += " w3-show";
  } else { 
    x.className = x.className.replace(" w3-show", "");
  }
}
</script>

</body>
</html>

C_Tut/home/templates/home/contact.html
{% extends '../home/baselayout.html' %}
{% load widget_tweaks %}
{% load static %}

{% block content %}
<link rel="stylesheet" type="text/css" href="{% static 'home/contactstyle.css' %}">
{% if message %}
    <div id="mod-message" class="w3-modal">
    <div class="w3-modal-content">
      <header class="w3-container w3-grey" style="z-index: 2;"> 
        <h2 class="w3-center">Done!!!</h2>
      </header>
      <div class="w3-container">
        <p class="w3-center">{{message}}</p>
      </div>
      <footer >
          <div class="w3-container w3-center w3-padding w3-light-grey w3-border-top">
          <button onclick="document.getElementById('mod-message').style.display='none'" 
        class="w3-center w3-button w3-black w3-padding">OK</button>
          </div>
      </footer>
    </div>
  </div>
{% endif %}

<div class="w3-container w3-center" style="padding:64px 16px">
  <h1 class="margin">Get in Touch with Us</h1>
    <div class="w3-card-2 w3-display-bottommiddle" style="max-width: 900px;min-width:360px;position: relative;">
    <form class="w3-container" action="{% url 'contact:contact' %}" method="post">
        {% csrf_token %}
        <div class="w3-row w3-margin-top">
                <div class="w3-col l3 m4 w3-center w3-margin-top"><label><b>First&nbsp;Name</b></label></div>
                <div class="w3-col l9 m8">{% render_field form.first_name class+="w3-input w3-border-bottom w3-margin-bottom" autocomplete="off" placeholder="Enter your first name" %}</div>
            </div>
        <div class="w3-row w3-margin-right">
                <div class="w3-col l3 m4  w3-center w3-margin-top"><label><b>Last&nbsp;Name</b></label></div>
                <div class="w3-col l9 m8">{% render_field form.last_name class+="w3-input w3-border-bottom w3-margin-bottom" autocomplete="off" placeholder="Enter your last name" %}</div>
            </div>
        <div class="w3-row">
                <div class="w3-col l3 m4 w3-center w3-margin-top"><label><b>Email</b></label></div>
                <div class="w3-col l9 m8">{% render_field form.email class+="w3-input w3-border-bottom w3-margin-bottom" autocomplete="off" placeholder="Email" type='email' %}</div>
            </div>
        <div class="w3-row">
                <div class="w3-col l3 m4 w3-margin-top"><label><b>Message</b></label></div>
                <div class="w3-col l9 m8">{% render_field form.message class+="w3-input w3-border w3-margin-bottom" autocomplete="off" placeholder="Your message" type="textarea" %}</div>
            </div>
    <button class="w3-btn w3-amber w3-padding-large w3-large w3-margin-top w3-margin-bottom w3-hover-grey" type="submit">Submit</button>
    </form>
    </div>
</div>
{% endblock %}

C_Tut/home/templates/home/homepage.html
{% extends '../home/baselayout.html' %}
{% load static %}

{% block content %}
<!-- First Grid -->
<div class="w3-row-padding w3-padding-64 w3-container">
  <div class="w3-content">
    <div class="w3-twothird">
      <h1>C &ensp;Programming</h1>
      <h5 class="w3-padding-32">C is a powerful general-purpose programming language. It is fast, portable and available in all platforms.
      C programming is highly efficient. That’s the main reason why it’s very popular despite being more than 40 years old. If you are new to programming, C is a good choice to start your programming journey.</h5>

        <p class="w3-text-grey">This is a comprehensive guide on how to get started in C programming language, why you should learn it and how you can learn it.</p>
        <h3>More information on C Language.Click Below!!</h3><br>
        <a href="#"><button class="w3-btn w3-amber w3-padding w3-hover-grey">Overview</button></a>
    </div>

    <div class="w3-third w3-center">
      <img src="{% static 'home/images/clogo.png' %}" class="w3-padding-64" style="height: 400px; width: 300px;">
    </div>
  </div>
</div>

<!-- Second Grid -->
<div class="w3-row-padding w3-light-grey w3-padding-64 w3-container">
  <div class="w3-content">
    <div class="w3-third w3-center">
      <i class="fa fa-coffee w3-padding-64 w3-text-black w3-margin-right"></i>
    </div>

    <div class="w3-twothird">
      <h1>What will you gain if you learn C?</h1>
      <h5 class="w3-padding-32">If you don’t know C, you don’t know what you are doing as a programmer. Sure, your application works fine and all. But, if you can’t say why while (*s++ = *p++); copies a string, you’re programming on a superstition. ( Joel Spolsky’s words, not mine ).
        <br>You will understand how a computer works.<br>C is the lingua franca of programming.<br>Opportunity to work on open source projects that impact millions of people.<br>You will write better programs.<br>You will find it much easier to learn other programming languages.</h5>
        
    </div>
  </div>
</div>

{% endblock %}

C_Tut/home/templates/home/team.html
{% extends '../home/baselayout.html' %}
{% load static %}

{% block content %}
<p>Welcome to Team page..</p>
{% endblock %}