C_Tut/C_Tut/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('accounts/',include('accounts.urls')),
    path('home/',include('home.urls')),
    path('tutorials/',include('tutorials.urls')),
    path('quiz/',include('quizz.urls')),
    path('contact/',include('contact.urls')),
    path('admin/', admin.site.urls),
]

C_Tut/accounts/urls.py
from django.urls import path
from . import views


app_name='accounts'
urlpatterns=[
    path('', views.index , name='index'),
    path( 'login/' , views.loginUser.as_view() , name='login'),
    path('signup',views.signupUser.as_view(),name='signup'),
    path('logout',views.logout_user.as_view(),name='logout'),
]

C_Tut/home/urls.py
from django.urls import path
from . import views


app_name='home'
urlpatterns=[
    path('',views.index,name='index'),
    path('about',views.about,name="about"),
    path('team',views.team,name="team"),
]

C_Tut/quizz/urls.py
from django.urls import path
from .views import QuizTake

app_name='quizz'
urlpatterns=[
    #quiz/3/
    path('<int:tutorial_id>/',view=QuizTake.as_view(),name='quiz_question'),
]

C_Tut/tutorials/urls.py
from django.urls import path
from . import views

app_name='tutorials'
urlpatterns=[
    #tutorials/stu_home/
    path('stu_home',views.stu_home,name="stu_home"),
    #tutorials/3/
    path('<int:tutorial_id>/',views.show_tutorial,name="show_tutorial"),
    #tutorials/arithmetic_example
    path('arithmetic_example',views.arithmetic_example,name="arithmetic_example"),
    #tutorials/arithmetic_example
    path('relational_example',views.relational_example,name="relational_example"),
    #tutorials/logical_example
    path('logical_example',views.logical_example,name="logical_example"),
    #tutorials/bitwise_example
    path('bitwise_example',views.bitwise_example,name="bitwise_example"),
    #tutorials/assignment_example
    path('assignment_example',views.assignment_example,name="assignment_example"),
    #tutorials/misc_example
    path('misc_example',views.misc_example,name="misc_example"),
    #tutorials/precedence_example
    path('precedence_example',views.precedence_example,name="precedence_example"),
    #tutorials/if_statement
    path('if_statement',views.if_statement,name="if_statement"),
     #tutorials/ifelse_statement
    path('ifelse_statement',views.ifelse_statement,name="ifelse_statement"),
    #tutorials/nestedif_statement
    path('nestedif_statement',views.nestedif_statement,name="nestedif_statement"),
    #tutorials/switch_statement
    path('switch_statement',views.switch_statement,name="switch_statement"),
    #tutorials/nestedswitch_statement
    path('nestedswitch_statement',views.nestedswitch_statement,name="nestedswitch_statement"),
]

C_Tut/tutorials/models.py
from django.db import models

# Create your models here.
class Tutorial(models.Model):
    name=models.CharField(max_length=300)
    html_name=models.CharField(max_length=300)
    created_date=models.DateTimeField('date published')
    
    def __str__(self):
        return self.name

C_Tut/tutorials/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse, HttpResponseRedirect
from django.template.loader import render_to_string
from django.contrib.auth.decorators import login_required
from django.views.decorators.cache import never_cache
from home.models import CPerson,student
from django.contrib.auth.models import User
from .models import Tutorial
# Create your views here
#tut_list=['Program structure','Basic Syntax','Datatypes','variables','Storage classes','Operators','Decision making','Loops','Functions','Scope rules','Arrays','Pointers','String','Structures','Unions','Bit Fields','Typedef','Input/Output','File I/O','Preprocessors','Header Files','Type casting','Error Handling','Recurssion','Variable Arguments','Memory management','Command Line Argument']
#@login_required(redirect_field_name='login')
@never_cache
def stu_home(request):
    if request.user.is_authenticated:
        try:
            cperson=CPerson.objects.get(user=request.user)
        except:
            return HttpResponse("You're not allowed to view this page.........")
        if cperson.type=='student':
            activeuser=student.objects.get(cperson=cperson)
            s="stu"
        if request.user.is_active and s=="stu":
            stu=True
            tut_list=Tutorial.objects.all()
            context={
                'stu_first_name': request.user.first_name,
                'stu_last_name': request.user.last_name,
                'stu_email': request.user.email,
                'stu_collagename': activeuser.collage_name,
                'stu_progress': activeuser.progress,
                'tut_list':tut_list,
                'stu':stu,
            }
            return render(request,'tutorials/stu_home.html',context)
    else:
        return redirect('accounts:login')
    
def show_tutorial(request,tutorial_id):
    tut=True
    if request.user.is_authenticated:
        try:
            cperson=CPerson.objects.get(user=request.user)
        except:
            return HttpResponse("You're not allowed to view this page.........")
        if cperson.type=='student':
            activeuser=student.objects.get(cperson=cperson)
            s="stu"
        if request.user.is_active and s=="stu":
            tut_list=Tutorial.objects.all()
            tutorial=Tutorial.objects.get(pk=tutorial_id)
            tut_name=tutorial.name
            temp_name=tutorial.html_name
            pre_tut=get_pretut(tut_id=tutorial_id)
            next_tut=get_nexttut(tut_id=tutorial_id)
            preid=pre_tut.id
            nextid=next_tut.id
            pre_link = str(preid)
            next_link = str(nextid)
            stu_progress=activeuser.progress
            enable=True
            if is_progresstemplate(tutorial_id,stu_progress):
                enable=False
            context={
                'tut_id':tutorial_id,
                'tut_name':tut_name,
                'pre_link':pre_link,
                'next_link':next_link,
                'tut_list':tut_list,
                'stu_progress': stu_progress,
                'enable':enable,
                'tut':tut,
            }
            return render(request,temp_name,context)
    else:
        return redirect('accounts:login')
    
    
def get_pretut(tut_id):
    if tut_id==1:
        return Tutorial.objects.get(pk=1)
    while True:
        tut_id=tut_id-1
        pre_tut=Tutorial.objects.filter(pk=tut_id).first()
        if pre_tut:
            return pre_tut
        
def get_nexttut(tut_id):
    while True:
        tut_id=tut_id+1
        next_tut=Tutorial.objects.filter(pk=tut_id).first()
        if next_tut:
            return next_tut
        

def is_progresstemplate(tut_id,progress):
    c=0
    temp_id=1
    while temp_id<=tut_id:
        if Tutorial.objects.filter(pk=temp_id).first():
            c=c+1
        temp_id=temp_id+1
    if c==progress:
        return True
    else:
        return False
        
def arithmetic_example(request):
    if request.user.is_authenticated:
        try:
            cperson=CPerson.objects.get(user=request.user)
        except:
            return HttpResponse("You're not allowed to view this page.........")
        if cperson.type=='student':
            activeuser=student.objects.get(cperson=cperson)
            s="stu"
        if request.user.is_active and s=="stu":
            tut_list=Tutorial.objects.all()
            temp_name="tutorials/arithmetic_example.html"
            context={
                'tut_list':tut_list,
                'stu_progress': activeuser.progress,
            }
            return render(request,temp_name,context)
    else:
        return redirect('accounts:login')
    
def relational_example(request):
    if request.user.is_authenticated:
        try:
            cperson=CPerson.objects.get(user=request.user)
        except:
            return HttpResponse("You're not allowed to view this page.........")
        if cperson.type=='student':
            activeuser=student.objects.get(cperson=cperson)
            s="stu"
        if request.user.is_active and s=="stu":
            tut_list=Tutorial.objects.all()
            temp_name="tutorials/relational_example.html"
            context={
                'tut_list':tut_list,
                'stu_progress': activeuser.progress,
            }
            return render(request,temp_name,context)
    else:
        return redirect('accounts:login')
    
def logical_example(request):
    if request.user.is_authenticated:
        try:
            cperson=CPerson.objects.get(user=request.user)
        except:
            return HttpResponse("You're not allowed to view this page.........")
        if cperson.type=='student':
            activeuser=student.objects.get(cperson=cperson)
            s="stu"
        if request.user.is_active and s=="stu":
            tut_list=Tutorial.objects.all()
            temp_name="tutorials/logical_example.html"
            context={
                'tut_list':tut_list,
                'stu_progress': activeuser.progress,
            }
            return render(request,temp_name,context)
    else:
        return redirect('accounts:login')
    
def bitwise_example(request):
    if request.user.is_authenticated:
        try:
            cperson=CPerson.objects.get(user=request.user)
        except:
            return HttpResponse("You're not allowed to view this page.........")
        if cperson.type=='student':
            activeuser=student.objects.get(cperson=cperson)
            s="stu"
        if request.user.is_active and s=="stu":
            tut_list=Tutorial.objects.all()
            temp_name="tutorials/bitwise_example.html"
            context={
                'tut_list':tut_list,
                'stu_progress': activeuser.progress,
            }
            return render(request,temp_name,context)
    else:
        return redirect('accounts:login')
    
    
def assignment_example(request):
    if request.user.is_authenticated:
        try:
            cperson=CPerson.objects.get(user=request.user)
        except:
            return HttpResponse("You're not allowed to view this page.........")
        if cperson.type=='student':
            activeuser=student.objects.get(cperson=cperson)
            s="stu"
        if request.user.is_active and s=="stu":
            tut_list=Tutorial.objects.all()
            temp_name="tutorials/assignment_example.html"
            context={
                'tut_list':tut_list,
                'stu_progress': activeuser.progress,
            }
            return render(request,temp_name,context)
    else:
        return redirect('accounts:login')
    
def misc_example(request):
    if request.user.is_authenticated:
        try:
            cperson=CPerson.objects.get(user=request.user)
        except:
            return HttpResponse("You're not allowed to view this page.........")
        if cperson.type=='student':
            activeuser=student.objects.get(cperson=cperson)
            s="stu"
        if request.user.is_active and s=="stu":
            tut_list=Tutorial.objects.all()
            temp_name="tutorials/misc_example.html"
            context={
                'tut_list':tut_list,
                'stu_progress': activeuser.progress,
            }
            return render(request,temp_name,context)
    else:
        return redirect('accounts:login')
    
def precedence_example(request):
    if request.user.is_authenticated:
        try:
            cperson=CPerson.objects.get(user=request.user)
        except:
            return HttpResponse("You're not allowed to view this page.........")
        if cperson.type=='student':
            activeuser=student.objects.get(cperson=cperson)
            s="stu"
        if request.user.is_active and s=="stu":
            tut_list=Tutorial.objects.all()
            temp_name="tutorials/precedence_example.html"
            context={
                'tut_list':tut_list,
                'stu_progress': activeuser.progress,
            }
            return render(request,temp_name,context)
    else:
        return redirect('accounts:login')
    
def if_statement(request):
    if request.user.is_authenticated:
        try:
            cperson=CPerson.objects.get(user=request.user)
        except:
            return HttpResponse("You're not allowed to view this page.........")
        if cperson.type=='student':
            activeuser=student.objects.get(cperson=cperson)
            s="stu"
        if request.user.is_active and s=="stu":
            tut_list=Tutorial.objects.all()
            temp_name="tutorials/if_statement.html"
            context={
                'tut_list':tut_list,
                'stu_progress': activeuser.progress,
            }
            return render(request,temp_name,context)
    else:
        return redirect('accounts:login')
    
def ifelse_statement(request):
    if request.user.is_authenticated:
        try:

C_Tut/tutorials/templates/tutorials/nestedif_statement.html
{% extends '../tutorials/tutbaselayout.html' %}
{% load static %}

{% block content %}
<h2 class="w3-border-top w3-border-bottom">nested if statements</h2>
<p>It is always legal in C programming to <b>nest</b> if-else statements, which means you can use one if or else if statement inside another if or else if statement(s).</p>
<h3><b>Syntax</b></h3>
<p>The syntax for a <b>nested if</b> statement is as follows −</p>
<div class="w3-example">
<pre>if( boolean_expression 1) {

   /* Executes when the boolean expression 1 is true */
   if(boolean_expression 2) {
      /* Executes when the boolean expression 2 is true */
   }
}</pre></div>
<p>You can nest <b>else if...else</b> in the similar way as you have nested if statements.</p>
<div class="w3-example">
<h3>Example</h3>
<div class="w3-code">
    <pre><span class="com">#include</span> <span class="str">&#60;stdio.h&#62;</span>
 
<span class="kwd">int</span> main <span class="pun">() {</span>

   <span class="com">/* local variable definition */</span>
   <span class="kwd">int</span> a <span class="pun">=</span> 100<span class="pun">;</span>
   <span class="kwd">int</span> b <span class="pun">=</span> 200<span class="pun">;</span>
 
   <span class="com">/* check the boolean condition */</span>
   <span class="kwd">if</span><span class="pun">(</span> a <span class="pun">==</span> 100 <span class="pun">) {</span>
   
      <span class="com">/* if condition is true then check the following */</span>
      <span class="kwd">if</span><span class="pun">(</span> b <span class="pun">==</span> 200 <span class="pun">) {</span>
         <span class="com">/* if condition is true then print the following */</span>
         printf<span class="pun">(</span><span class="str">"Value of a is 100 and b is 200\n"</span> <span class="pun">);</span>
      <span class="pun">}</span>
   <span class="pun">}</span>
   
   printf<span class="pun">(</span><span class="str">"Exact value of a is : %d\n"</span>, a<span class="pun">);</span>
   printf<span class="pun">(</span><span class="str">"Exact value of b is : %d\n"</span>, b<span class="pun">);</span>
 
   <span class="kwd">return</span> 0<span class="pun">;</span>
<span class="pun">}</span></pre></div>
</div>
<p>When the above code is compiled and executed, it produces the following result −</p>
<div class="w3-example">
<pre>Value of a is 100 and b is 200
Exact value of a is : 100
Exact value of b is : 200</pre></div>
{% endblock %}

C_Tut/tutorials/templates/tutorials/operators.html
{% extends '../tutorials/tutbaselayout.html' %}
{% load static %}

{% block content %}
<p>An operator is a symbol that tells the compiler to perform specific mathematical or logical functions. C language is rich in built-in operators and provides the following types of operators −</p>
<ul>
    <li>Arithmetic Operators</li>
    <li>Relational Operators</li>
    <li>Logical Operators</li>
    <li>Bitwise Operators</li>
    <li>Assignment Operators</li>
    <li>Misc Operators</li>
</ul>
<p>We will, in this chapter, look into the way each operator works.</p>
<h2 class="w3-border-top w3-border-bottom">Arithmetic Operators</h2>
<p>The following table shows all the arithmetic operators supported by the C language. Assume variable <b>A</b> holds 10 and variable <b>B</b> holds 20 then −</p>
<p><a href="{% url 'tutorials:arithmetic_example' %}"><h4>Show Examples</h4></a></p>
<table class="table table-bordered" style="text-align: center">
<tbody>
    <tr>
        <th>Operator</th><th>Description</th><th>Example</th>
    </tr>
    <tr>
        <td>+</td> <td>	Adds two operands.</td><td> 	A + B = 30</td>
    </tr>
    <tr>
        <td>− </td><td>	Subtracts second operand from the first. </td><td>	A − B = -10</td>
    </tr>
    <tr>
        <td>*</td><td> 	Multiplies both operands.</td><td> 	A * B = 200</td>
    </tr>
    <tr>
        <td>/ </td><td>	Divides numerator by de-numerator. </td><td>	B / A = 2</td>
    </tr>
    <tr>
        <td>% </td><td>	Modulus Operator and remainder of after an integer division. </td><td>	B % A = 0</td>
    </tr>
    <tr>
        <td>++ </td><td>	Increment operator increases the integer value by one.</td><td> 	A++ = 11</td>
    </tr>
    <tr>
        <td>-- </td><td>	Decrement operator decreases the integer value by one.</td><td> 	A-- = 9</td>
    </tr>
    </tbody>
</table>
<h2 class="w3-border-top w3-border-bottom">Relational Operators</h2>
<p>The following table shows all the relational operators supported by C. Assume variable <b>A</b> holds 10 and variable <b>B</b> holds 20 then −</p>
<p><a href="{% url 'tutorials:relational_example' %}"><h4>Show Examples</h4></a></p>
<table class="table table-bordered" style="text-align: center">
<tbody>
    <tr>
        <th>Operator</th><th>Description</th><th>Example</th>
    </tr>
    <tr>
        <td>==</td> <td>	Checks if the values of two operands are equal or not. If yes, then the condition becomes true.</td><td> 	(A == B) is not true.</td>
    </tr>
    <tr>
        <td>!= </td><td>	Checks if the values of two operands are equal or not. If the values are not equal, then the condition becomes true. </td><td>	(A != B) is true.</td>
    </tr>
    <tr>
        <td>></td><td> 	Checks if the value of left operand is greater than the value of right operand. If yes, then the condition becomes true.</td><td> 	(A > B) is not true.</td>
    </tr>
    <tr>
        <td>&#60; </td><td>	Checks if the value of left operand is less than the value of right operand. If yes, then the condition becomes true. </td><td>	(A &#60; B) is true.</td>
    </tr>
    <tr>
        <td>>= </td><td>	Checks if the value of left operand is greater than or equal to the value of right operand. If yes, then the condition becomes true. </td><td>	(A >= B) is not true.</td>
    </tr>
    <tr>
        <td>&#60;= </td><td>	Checks if the value of left operand is less than or equal to the value of right operand. If yes, then the condition becomes true.</td><td> 	(A &#60;= B) is true.</td>
    </tr>
    </tbody>
</table>
<h2 class="w3-border-top w3-border-bottom">Logical Operators</h2>
<p>Following table shows all the logical operators supported by C language. Assume variable <b>A</b> holds 1 and variable <b>B</b> holds 0, then −</p>
<p><a href="{% url 'tutorials:logical_example' %}"><h4>Show Examples</h4></a></p>
<table class="table table-bordered" style="text-align: center">
<tbody>
    <tr>
        <th>Operator</th><th>Description</th><th>Example</th>
    </tr>
    <tr>
        <td>&&</td> <td>	Called Logical AND operator. If both the operands are non-zero, then the condition becomes true.</td><td> 	(A && B) is false.</td>
    </tr>
    <tr>
        <td>|| </td><td>	Called Logical OR Operator. If any of the two operands is non-zero, then the condition becomes true. </td><td>	(A || B) is true.</td>
    </tr>
    <tr>
        <td>!</td><td> 	Called Logical NOT Operator. It is used to reverse the logical state of its operand. If a condition is true, then Logical NOT operator will make it false.</td><td> 	!(A && B) is true.</td>
    </tr>
    </tbody>
</table>
<h2 class="w3-border-top w3-border-bottom">Bitwise Operators</h2>
<p>Bitwise operator works on bits and perform bit-by-bit operation. The truth tables for &, |, and ^ is as follows −</p>
<table class="table table-bordered" style="text-align: center">
<tbody>
    <tr>
        <th>p</th><th>q</th><th>p & q</th><th>p | q</th><th>p ^ q</th>
    </tr>
    <tr>
        <td>0</td> <td>	0</td><td>0</td><td>0</td><td>0</td>
    </tr>
    <tr>
        <td>0</td> <td>	1</td><td>0</td><td>1</td><td>1</td>
    </tr>
    <tr>
        <td>1</td> <td>	0</td><td>0</td><td>1</td><td>1</td>
    </tr>
    <tr>
        <td>1</td> <td>	1</td><td>1</td><td>1</td><td>0</td>
    </tr>
    </tbody>
</table>
<p>Assume A = 60 and B = 13 in binary format, they will be as follows −</p>
<p>A = 0011 1100</p>

<p>B = 0000 1101</p>

<p>-----------------</p>

<p>A&B = 0000 1100</p>

<p>A|B = 0011 1101</p>

<p>A^B = 0011 0001</p>

<p>~A = 1100 0011</p>

<p>The following table lists the bitwise operators supported by C. Assume variable 'A' holds 60 and variable 'B' holds 13, then −</p>
<p><a href="{% url 'tutorials:bitwise_example' %}"><h4>Show Examples</h4></a></p>
<table class="table table-bordered" style="text-align: center">
<tbody>
    <tr>
        <th>Operator</th><th>Description</th><th>Example</th>
    </tr>
    <tr>
        <td>&</td> <td>	Binary AND Operator copies a bit to the result if it exists in both operands. </td><td> 	(A & B) = 12, i.e., 0000 1100</td>
    </tr>
    <tr>
        <td>| </td><td>	Binary OR Operator copies a bit if it exists in either operand. </td><td>	(A | B) = 61, i.e., 0011 1101</td>
    </tr>
    <tr>
        <td>^</td><td> 	Binary XOR Operator copies the bit if it is set in one operand but not both. </td><td> 	(A ^ B) = 49, i.e., 0011 0001</td>
    </tr>
    <tr>
        <td>~</td><td>Binary One's Complement Operator is unary and has the effect of 'flipping' bits. </td><td>	(~A ) = ~(60), i.e,. -0111101</td>
    </tr>
    <tr>
        <td>&#60;&#60; </td><td>	Binary Left Shift Operator. The left operands value is moved left by the number of bits specified by the right operand. </td><td>	A &#60;&#60; 2 = 240 i.e., 1111 0000</td>
    </tr>
    <tr>
        <td>>> </td><td>	Binary Right Shift Operator. The left operands value is moved right by the number of bits specified by the right operand.</td><td> 	A >> 2 = 15 i.e., 0000 1111</td>
    </tr>
    </tbody>
</table>
<h2 class="w3-border-top w3-border-bottom">Assignment Operators</h2>
<p>The following table lists the assignment operators supported by the C language −</p>
<p><a href="{% url 'tutorials:assignment_example' %}"><h4>Show Examples</h4></a></p>
<table class="table table-bordered" style="text-align: center">
<tbody>
    <tr>
        <th>Operator</th><th>Description</th><th>Example</th>
    </tr>
    <tr>
        <td>=</td> <td>	Simple assignment operator. Assigns values from right side operands to left side operand</td><td> 	C = A + B will assign the value of A + B to C</td>
    </tr>
    <tr>
        <td>+= </td><td>	Add AND assignment operator. It adds the right operand to the left operand and assign the result to the left operand. </td><td>	C += A is equivalent to C = C + A</td>
    </tr>
    <tr>
        <td>-=</td><td> 	Subtract AND assignment operator. It subtracts the right operand from the left operand and assigns the result to the left operand.</td><td> 	C -= A is equivalent to C = C - A</td>
    </tr>
    <tr>
        <td>*=</td><td> 	Multiply AND assignment operator. It multiplies the right operand with the left operand and assigns the result to the left operand.</td><td> 	C *= A is equivalent to C = C * A</td>
    </tr>
    <tr>
        <td>/=</td><td> 	Divide AND assignment operator. It divides the left operand with the right operand and assigns the result to the left operand.</td><td> 	C /= A is equivalent to C = C / A</td>
    </tr>
    <tr>
        <td>%=</td><td> 	Modulus AND assignment operator. It takes modulus using two operands and assigns the result to the left operand.</td><td> 	C %= A is equivalent to C = C % A</td>
    </tr>
    <tr>
        <td>&#60;&#60;=</td><td> 	Left shift AND assignment operator.</td><td> 	C &#60;&#60;= 2 is same as C = C &#60;&#60; 2</td>
    </tr>
    <tr>
        <td>>>=</td><td> 	Right shift AND assignment operator.</td><td> 	C >>= 2 is same as C = C >> 2</td>
    </tr>
    <tr>
        <td>&=</td><td> 	Bitwise AND assignment operator.</td><td> C &= 2 is same as C = C & 2</td>
    </tr>
    <tr>
        <td>^=</td><td> 	Bitwise exclusive OR and assignment operator.</td><td> 	C ^= 2 is same as C = C ^ 2</td>
    </tr>
    <tr>
        <td>|=</td><td> 	Bitwise inclusive OR and assignment operator.</td><td> 	C |= 2 is same as C = C | 2</td>
    </tr>
    </tbody>
</table>
<h2 class="w3-border-top w3-border-bottom">Misc Operators ↦ sizeof & ternary</h2>
<p>Besides the operators discussed above, there are a few other important operators including <b>sizeof</b> and <b>? :</b> supported by the C Language.</p>
<p><a href="{% url 'tutorials:misc_example' %}"><h4>Show Examples</h4></a></p>
<table class="table table-bordered" style="text-align: center">
<tbody>
    <tr>
        <th>Operator</th><th>Description</th><th>Example</th>
    </tr>
    <tr>
        <td>sizeof()</td> <td>	Returns the size of a variable.</td><td> 	sizeof(a), where a is integer, will return 4.</td>
    </tr>
    <tr>
        <td>&</td><td>	Returns the address of a variable.</td><td>	&a; returns the actual address of the variable.</td>
    </tr>
    <tr>
        <td>*</td><td> 	Pointer to a variable.</td><td> 	*a;</td>
    </tr>
    <tr>
        <td>?:</td><td> 	Conditional Expression.</td><td> 	If Condition is true ? then value X : otherwise value Y</td>
    </tr>
    </tbody>
</table>
<h2 class="w3-border-top w3-border-bottom">Operators Precedence in C</h2>
<p>Operator precedence determines the grouping of terms in an expression and decides how an expression is evaluated. Certain operators have higher precedence than others; for example, the multiplication operator has a higher precedence than the addition operator.
</p><p>
For example, x = 7 + 3 * 2; here, x is assigned 13, not 20 because operator * has a higher precedence than +, so it first gets multiplied with 3*2 and then adds into 7.
</p><p>
Here, operators with the highest precedence appear at the top of the table, those with the lowest appear at the bottom. Within an expression, higher precedence operators will be evaluated first.</p>
<p><a href="{% url 'tutorials:precedence_example' %}"><h4>Show Examples</h4></a></p>
<table class="table table-bordered" style="text-align: center">
<tbody>
    <tr>
        <th>Category</th><th>Description</th><th>Associativity</th>
    </tr>
    <tr>
        <td>Postfix</td> <td>	() [] -> . ++ - -</td><td> 	Left to right</td>
    </tr>
    <tr>
        <td>Unary</td><td>	+ - ! ~ ++ - - (type)* & sizeof</td><td>Right to left</td>
    </tr>
    <tr>
        <td>Multiplicative</td> <td>	* / %</td><td> 	Left to right</td>
    </tr>
    <tr>
        <td>Additive</td> <td>	+-</td><td> 	Left to right</td>
    </tr>
    <tr>
        <td>Shift</td> <td>	&#60;&#60;>></td><td> 	Left to right</td>
    </tr>
    <tr>
        <td>Relational</td> <td>&#60;&#60;=>>=</td><td> 	Left to right</td>
    </tr>
    <tr>
        <td>Bitwise AND</td> <td>&</td><td> 	Left to right</td>
    </tr>
    <tr>
        <td>Bitwise XOR</td> <td>^</td><td> 	Left to right</td>
    </tr>
    <tr>
        <td>Bitwise OR</td> <td>|</td><td> 	Left to right</td>
    </tr>
    <tr>
        <td>Logical AND</td> <td>&&</td><td> 	Left to right</td>
    </tr>
    <tr>
        <td>Logical OR</td> <td>||</td><td> 	Left to right</td>
    </tr>
    <tr>
        <td>Conditional</td> <td>?:</td><td> 	Right to left</td>
    </tr>
    <tr>
        <td>Assignment</td> <td>= += -= *= /= %=>>= &#60;&#60;= &= ^= |=</td><td> 	Right to left</td>
    </tr>
    <tr>
        <td>Comma</td> <td>,</td><td> 	Left to right</td>
    </tr>
    </tbody>
</table>
{% endblock %}