C_Tut/C_Tut/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('accounts/',include('accounts.urls')),
    path('home/',include('home.urls')),
    path('tutorials/',include('tutorials.urls')),
    path('quiz/',include('quizz.urls')),
    path('contact/',include('contact.urls')),
    path('admin/', admin.site.urls),
]

C_Tut/accounts/urls.py
from django.urls import path
from . import views


app_name='accounts'
urlpatterns=[
    path('', views.index , name='index'),
    path( 'login/' , views.loginUser.as_view() , name='login'),
    path('signup',views.signupUser.as_view(),name='signup'),
    path('logout',views.logout_user.as_view(),name='logout'),
]

C_Tut/home/urls.py
from django.urls import path
from . import views


app_name='home'
urlpatterns=[
    path('',views.index,name='index'),
    path('about',views.about,name="about"),
    path('team',views.team,name="team"),
]

C_Tut/quizz/urls.py
from django.urls import path
from .views import QuizTake

app_name='quizz'
urlpatterns=[
    #quiz/3/
    path('<int:tutorial_id>/',view=QuizTake.as_view(),name='quiz_question'),
]

C_Tut/tutorials/urls.py
from django.urls import path
from . import views

app_name='tutorials'
urlpatterns=[
    #tutorials/stu_home/
    path('stu_home',views.stu_home,name="stu_home"),
    #tutorials/3/
    path('<int:tutorial_id>/',views.show_tutorial,name="show_tutorial"),
    #tutorials/arithmetic_example
    path('arithmetic_example',views.arithmetic_example,name="arithmetic_example"),
    #tutorials/arithmetic_example
    path('relational_example',views.relational_example,name="relational_example"),
    #tutorials/logical_example
    path('logical_example',views.logical_example,name="logical_example"),
    #tutorials/bitwise_example
    path('bitwise_example',views.bitwise_example,name="bitwise_example"),
    #tutorials/assignment_example
    path('assignment_example',views.assignment_example,name="assignment_example"),
    #tutorials/misc_example
    path('misc_example',views.misc_example,name="misc_example"),
    #tutorials/precedence_example
    path('precedence_example',views.precedence_example,name="precedence_example"),
    #tutorials/if_statement
    path('if_statement',views.if_statement,name="if_statement"),
     #tutorials/ifelse_statement
    path('ifelse_statement',views.ifelse_statement,name="ifelse_statement"),
    #tutorials/nestedif_statement
    path('nestedif_statement',views.nestedif_statement,name="nestedif_statement"),
    #tutorials/switch_statement
    path('switch_statement',views.switch_statement,name="switch_statement"),
    #tutorials/nestedswitch_statement
    path('nestedswitch_statement',views.nestedswitch_statement,name="nestedswitch_statement"),
]

C_Tut/quizz/forms.py
from django import forms
from django.forms.widgets import RadioSelect, Textarea


class QuestionForm(forms.Form):
    def __init__(self, question, *args, **kwargs):
        super(QuestionForm, self).__init__(*args, **kwargs)
        choice_list = [x for x in question.get_answers_list()]
        self.fields["answers"] = forms.ChoiceField(choices=choice_list,widget=RadioSelect)

C_Tut/quizz/views.py
import random

from django.contrib.auth.decorators import login_required, permission_required
from django.core.exceptions import PermissionDenied
from django.shortcuts import get_object_or_404, render
from django.utils.decorators import method_decorator
from django.views.generic import DetailView, ListView, TemplateView, FormView

from .forms import QuestionForm
from .models import Quiz, Progresss, Sitting, Question
from tutorials.models import Tutorial
from home.models import student,CPerson

class QuizTake(FormView):
    form_class = QuestionForm
    template_name = 'quizz/question.html'
    result_template_name = 'quizz/result.html'
    single_complete_template_name = 'single_complete.html'

    def dispatch(self, request, *args, **kwargs):
        self.tutorial = get_object_or_404(Tutorial, id=self.kwargs['tutorial_id'])
        self.quiz=self.tutorial.quiz

        try:
            self.logged_in_user = self.request.user.is_authenticated()
        except TypeError:
            self.logged_in_user = self.request.user.is_authenticated

        if self.logged_in_user:
            cperson=CPerson.objects.get(user=request.user)
            Student=student.objects.get(cperson=cperson)
            self.sitting = Sitting.objects.user_sitting(Student ,self.quiz)

        if self.sitting is False:
            return render(request, self.single_complete_template_name)

        return super(QuizTake, self).dispatch(request, *args, **kwargs)

    def get_form(self, *args, **kwargs):
        if self.logged_in_user:
            self.question = self.sitting.get_first_question()
            self.progress = self.sitting.progress()
            
        form_class = self.form_class

        return form_class(**self.get_form_kwargs())

    def get_form_kwargs(self):
        kwargs = super(QuizTake, self).get_form_kwargs()

        return dict(kwargs, question=self.question)

    def form_valid(self, form):
        if self.logged_in_user:
            self.form_valid_user(form)
            if self.sitting.get_first_question() is False:
                return self.final_result_user()

        self.request.POST = {}

        return super(QuizTake, self).get(self, self.request)

    def get_context_data(self, **kwargs):
        context = super(QuizTake, self).get_context_data(**kwargs)
        context['tut_list']=Tutorial.objects.all()
        context['question'] = self.question
        context['quiz'] = self.quiz
        cperson=CPerson.objects.get(user=self.request.user)
        Student=student.objects.get(cperson=cperson)
        context['stu_progress']=Student.progress
        if hasattr(self, 'previous'):
            context['previous'] = self.previous
        if hasattr(self, 'progress'):
            context['progress'] = self.progress
        return context

    def form_valid_user(self, form):
        cperson=CPerson.objects.get(user=self.request.user)
        Student=student.objects.get(cperson=cperson)
        progresss, c = Progresss.objects.get_or_create(student=Student)
        guess = form.cleaned_data['answers']
        is_correct = self.question.check_if_correct(guess)

        if is_correct is True:
            self.sitting.add_to_score(1)
            progresss.update_score(self.question, 1, 1)
        else:
            self.sitting.add_incorrect_question(self.question)
            progresss.update_score(self.question, 0, 1)

        if self.quiz.answers_at_end is not True:
            self.previous = {'previous_answer': guess,
                             'previous_outcome': is_correct,
                             'previous_question': self.question,
                             'answers': self.question.get_answers(),
                             'question_type': {self.question
                                               .__class__.__name__: True}}
        else:
            self.previous = {}

        self.sitting.add_user_answer(self.question, guess)
        self.sitting.remove_first_question()

    def final_result_user(self):
        cperson=CPerson.objects.get(user=self.request.user)
        Student=student.objects.get(cperson=cperson)
        if self.sitting.check_if_passed and Student.progress==self.get_tut_rank():
            Student.progress=Student.progress+1
            Student.save()
        tut_list=Tutorial.objects.all()
        results = {
            'quiz': self.quiz,
            'score': self.sitting.get_current_score,
            'max_score': self.sitting.get_max_score,
            'percent': self.sitting.get_percent_correct,
            'sitting': self.sitting,
            'previous': self.previous,
            'tut_list':tut_list,
            'stu_progress':Student.progress,
        }
        
        self.sitting.mark_quiz_complete()

        if self.quiz.answers_at_end:
            results['questions'] = self.sitting.get_questions(with_answers=True)
            results['incorrect_questions'] = self.sitting.get_incorrect_questions

        return render(self.request, self.result_template_name, results)
    
    def get_tut_rank(self):
        c=1
        rank=0
        while c<=self.tutorial.id:
            curr_tut=Tutorial.objects.filter(pk=c).first()
            if curr_tut:
                rank=rank+1
            c=c+1
        return rank

C_Tut/quizz/templates/quizz/base.html
{% load i18n %}
<!DOCTYPE html>
{% load static %}
<html style="height: 100%;" lang="en-US">
<head>
    <title>{% trans "Quiz" %} | {% block title %}{% endblock %}</title>
    <meta name="description" content="{% block description %}{% endblock %}">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" type="text/css" href="{% static 'quizz/w3.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'quizz/theme.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'quizz/quizzstyle.css' %}">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    </head>
    <body style="position:relative;min-height: 100%;top: 0px;">
        
        <!--logo bar-->
        <div class="w3-container w3-border-sand w3-theme-l1 top" id="logo_bar">
            <img src="{% static 'quizz/images/slogo.png' %}" class="w3-image" style="width: 250px;height: 80px; display: block;position: absolute;">
        </div>

            <!--navbar on large screen-->
            <div id="largenav" class="w3-card-2 topnav w3-theme" style="position: relative;top: 0px;">
            <div style="overflow: auto;">
    <div class="w3-bar" style="width: 100%;overflow: hidden;">
        <a class="w3-bar-item w3-button w3-left w3-hover-amber w3-xlarge w3-theme w3-hide-large" href="javascript:void(0)" onclick="w3_open('mySidebar')"><i class="fa fa-caret-square-o-right"></i></a>
        <a class="w3-bar-item w3-button w3-xlarge w3-hide-large w3-right w3-hover-amber w3-theme-d2" href="javascript:void(0);" onclick="openNav('smallnav')"><i class="fa fa-bars"></i></a>
        <form action="{% url 'accounts:logout' %}" method="post">
            {% csrf_token %}
            <button id="login" class="w3-bar-item w3-button w3-hover-amber w3-right w3-border w3-round-xlarge  w3-hide-small w3-hide-medium" type="submit"><i class="fa fa-sign-out"></i> Logout</button></form>
        <a href="#" id="services" class="w3-bar-item w3-button w3-hover-amber w3-right w3-padding-16 w3-hide-small w3-hide-medium">Refernces</a>
        <a href="#" id="contact" class="w3-bar-item w3-button w3-hover-amber w3-right w3-padding-16 w3-hide-small w3-hide-medium">Codingground</a>
        <a href="#" id ="about" class="w3-bar-item w3-button w3-hover-amber w3-right w3-padding-16 w3-hide-small w3-hide-medium">Exercise</a>
        <a href="#" id ="about" class="w3-bar-item w3-button w3-hover-amber w3-right w3-padding-16 w3-hide-small w3-hide-medium">Environment setup</a>
        <a href="{% url 'tutorials:stu_home' %}" id="home" class="w3-bar-item w3-button w3-amber w3-right w3-padding-16 w3-hide-small w3-hide-medium">Home</a>
        </div>
            </div>
            </div>
        
        <!--navbar on small-screen////id for signup is different in both size bar-->
        <div id="smallnav" class="w3-bar-block w3-theme-d2 w3-hide w3-hide-large">
    <a href="{% url 'tutorials:stu_home' %}" id="home" class="w3-bar-item w3-button w3-amber">Home</a>
    <a href="#" id ="about" class="w3-bar-item w3-button w3-hover-amber">Environment setup</a>
    <a href="#" id="contact" class="w3-bar-item w3-button w3-hover-amber">Exercise</a>
    <a href="#" id="services"class="w3-bar-item w3-button w3-hover-amber">Codingground</a>
            <a href="#" id ="about" class="w3-bar-item w3-button w3-hover-amber">References</a>
    <a href="#" id="slogin" class="w3-bar-item w3-button w3-hover-amber" onclick="document.getElementById('modlogin').style.display='block'"><i class="fa fa-sign-out"></i> Logout</a>
  </div>
        
        <!-- Content Sidebar -->
<div class="w3-sidebar w3-collapse w3-card-2 w3-theme-l1" id="mySidebar">
    <div class="w3-bar-block">
    <a href="javascript:void(0)" onclick="w3_close('mySidebar')" class="w3-button w3-right w3-xlarge w3-hide-large" title="Close Menu"><i class="fa fa-close"></i></a>
  <div class="w3-container">
    <h3 class="w3-margin-top">Tutorials</h3>
  </div>
        {% for x in tut_list %}
            {% if forloop.counter <= stu_progress %}
                <a class="w3-bar-item w3-button w3-block w3-hover-amber" href="/tutorials/{{x.id}}">{{x.name}}</a>
            {% else %}
                <a class="w3-bar-item w3-button w3-block w3-hover-amber w3-disabled" href="/tutorials/{{x.id}}" style="pointer-events: none">{{x.name}}</a>
            {% endif %}
        {% endfor %}
 <!-- <a class="w3-bar-item w3-button w3-block w3-hover-amber" href="#">{{stu_first_name}}</a>
  <a class="w3-bar-item w3-button w3-hover-amber" href="#">{{stu_progress}}</a>
  <a class="w3-bar-item w3-button w3-hover-amber" href="#">Program Structure</a>
  <a class="w3-bar-item w3-button w3-hover-amber" href="#">Basic Syntax</a>
  <a class="w3-bar-item w3-button w3-hover-amber" href="#">DataTypes</a>
  <a class="w3-bar-item w3-button w3-hover-amber" href="#">Variables</a>
  <a class="w3-bar-item w3-button w3-hover-amber" href="#">Storage Classes</a>
  <a class="w3-bar-item w3-button w3-hover-amber" href="#">Operators</a>
  <a class="w3-bar-item w3-button w3-hover-amber" href="#">Decision Making</a>
  <a class="w3-bar-item w3-button w3-hover-amber" href="#">Loops</a>
      <a class="w3-bar-item w3-button w3-hover-amber" href="#">Functions</a>
      <a class="w3-bar-item w3-button w3-hover-amber" href="#">Scope Rules</a>
      <a class="w3-bar-item w3-button w3-hover-amber" href="#">Arrays</a>
      <a class="w3-bar-item w3-button w3-hover-amber" href="#">Pointers</a>
      <a class="w3-bar-item w3-button w3-hover-amber" href="#">String</a>
      <a class="w3-bar-item w3-button w3-hover-amber" href="#">Structures</a>
      <a class="w3-bar-item w3-button w3-hover-amber" href="#">Unions</a>
      <a class="w3-bar-item w3-button w3-hover-amber" href="#">Bit Fields</a>
      <a class="w3-bar-item w3-button w3-hover-amber" href="#">Typedef</a>
      <a class="w3-bar-item w3-button w3-hover-amber" href="#">Input/Output</a>
      <a class="w3-bar-item w3-button w3-hover-amber" href="#">File I/O</a>
      <a class="w3-bar-item w3-button w3-hover-amber" href="#">Preprocessors</a>
      <a class="w3-bar-item w3-button w3-hover-amber" href="#">Header Files</a>
      <a class="w3-bar-item w3-button w3-hover-amber" href="#">Type Casting</a>
      <a class="w3-bar-item w3-button w3-hover-amber" href="#">Error handling</a>
      <a class="w3-bar-item w3-button w3-hover-amber" href="#">Recursion</a>
      <a class="w3-bar-item w3-button w3-hover-amber" href="#">Variable Arguments</a>
      <a class="w3-bar-item w3-button w3-hover-amber" href="#">Memory Management</a>
      <a class="w3-bar-item w3-button w3-hover-amber" href="#">CommandLine Argument</a>-->
    </div>
</div>
    <!-- Overlay effect when opening sidebar on small screens -->
<div class="w3-overlay w3-hide-large" onclick="w3_close('mySidebar')" style="cursor:pointer" title="close side menu" id="myOverlay"></div>

    <div id="main-content" class="w3-main w3-white" style="margin-left: 270px;">
        <div class="w3-row">
            <div id="main" class="w3-col" style="width: 80%;padding: 8px;">
         {% block content %}
        {% endblock %}
            </div>
        </div>
    </div>
        <script>
// Script for side main navigation
function w3_open(oid_name) 
    {
    if(oid_name=="smallnav")
        {
        var x = document.getElementById("smallnav");
        x.style.width = "500px";
        x.style.paddingTop = "10%";
        x.style.display = "block";
        }
    if(oid_name=="mySidebar")
        {
            if(document.getElementById("smallnav").className.indexOf("w3-show") == -1)
                {
                document.getElementById("mySidebar").style.display = "block";
                document.getElementById("myOverlay").style.display = "block";
                }
            else
                {
                document.getElementById("smallnav").className = document.getElementById("smallnav").className.replace(" w3-show", "");
                document.getElementById("mySidebar").style.display = "block";
                document.getElementById("myOverlay").style.display = "block";

                }
        }
    }
// Close side main navigation
function w3_close(id_name) {
    if(id_name=="mySidebar")
        {
            document.getElementById(id_name).style.display = "none";
            document.getElementById("myOverlay").style.display = "none";
        }
    else
        {
            document.getElementById(id_name).style.display = "none";
        }
}
// Used to toggle the main navigation on smaller screens when clicking on the menu button
function openNav(name) {
  var x = document.getElementById(name);
  if (x.className.indexOf("w3-show") == -1) {
    x.className += " w3-show";
  } else { 
    x.className = x.className.replace(" w3-show", "");
  }
}
</script>
    </body>
</html>

C_Tut/quizz/templates/quizz/correct_answer.html
{% load i18n %}
{% load static %}
{% if previous.answers %}

  {% if user_was_incorrect %}
    <div>
  	  <strong>{% trans "You answered the above question incorrectly" %}</strong>
    </div>
  {% endif %}
<div class="w3-responsive">
  <table class="w3-table-all w3-card-4">
    <tbody>
  	  {% for answer in previous.answers %}
        {% if answer.correct %}
  	    <tr>
  		  <td>{{ answer.content }}</td>
  		  <td><strong>{% trans "This is the correct answer" %}</strong></td>
        </tr>
        {% else %}
  		<tr>
      	  <td>{{ answer.content }}</td>
  		  <td>
  			{% if previous.question_type.MCQuestion %}
  			  {% if answer.id|add:"0" == previous.previous_answer|add:"0" %}
  			    {% trans "This was your answer." %}
  			  {% endif %}
  			{% endif %}
  		  </td>
  	  {% endif %}
  	    </tr>
  	{% endfor %}
    </tbody>
  </table>
</div>
{% endif %}

C_Tut/quizz/templates/quizz/question.html
{% extends '../quizz/base.html' %}
{% load static %}
{% load i18n %}
{% load quiz_tags %}

{% block title %} {{ quiz.title }} {% endblock %}
{% block description %} {{ quiz.title }} - {{ quiz.description }} {% endblock %}

{% block content %}

{% if question %}
{% if progress %}
<div style="float: right;">
{% trans "Question" %} {{ progress.0|add:1 }} {% trans "of" %} {{ progress.1 }}
</div>
{% endif %}

<p>
  <small>{% trans "Question category" %}:</small>
  <strong>{{ quiz.title }}</strong>
</p>
<p><h4>{{ question.content }}</h4></p>
{% if question.figure %}
    <img src="{{ question.figure.url }}" alt="{{ question.content }}" />
{% endif %}
{% if question.code %}
<div class="w3-example"><pre>{{question.code}}</pre></div>
{% endif %}
<form action="" method="POST">
{% csrf_token %}
  <input type=hidden name="question_id" value="{{ question.id }}">

  <ul style="list-style: none">

	{% for answer in form.answers %}
	  <li>
	    {{ answer }}
	  </li>
	{% endfor %}

  </ul>
  <input type="submit" value={% trans "Check" %} class="w3-btn w3-black w3-hover-amber" >
</form>
{% endif %}

{% endblock %}

C_Tut/quizz/templates/quizz/result.html
{% extends '../quizz/base.html' %}
{% load i18n %}

{% load quiz_tags %}

{% block title %} {{ quiz.title}} {% endblock %}
{% block description %} {% trans "Exam Results for" %} {{ quiz.title }} {% endblock %}

{% block content %}
{% if max_score %}

  <div>
	<h2>{% trans "Exam results" %}</h2>
	<p>
      <h4>{% trans "Exam title" %}: </h4>
	  <strong>{{ quiz.title }}</strong></p>

	<p><h4>
	  {% trans "You answered" %} {{ score }} {% trans "questions correctly out of" %} {{ max_score }}, {% trans "giving you" %} {{ percent }} {% trans "percent correct" %}
    </h4></p>

	{% if quiz.pass_mark %}
	<hr>
    <p><h4>{{ sitting.result_message }}</h4></p>
	<hr>

	{% endif %}

	<p>{% trans "Review the questions below and try the exam again in the future"%}.</p>

	{% if user.is_authenticated %}

	  <p>{% trans "The result of this exam will be stored in your progress section so you can review and monitor your progression" %}.</p>

	{% endif %}
  </div>


  {% endif %}
{% if questions %}

    {% for question in questions %}

      <p><h3>
		{{ question.content }}
      </h3></p>

	  {% correct_answer_for_all question %}

      {% if question.user_answer %}
      <p>{% trans "Your answer" %}: {{ question|answer_choice_to_string:question.user_answer }}</p>
      {% endif %}

	  <p><strong>{% trans "Explanation" %}:</strong></p>
	  <div style="background-color: #fcf8e3;">
		<p>{{ question.explanation|safe }}</p>
	  </div>

	  <hr>

  {% endfor %}

{% endif %}
<div class="w3-example w3-center">
<h4>Wanna give quiz again??</h4>
    <a href="{% url 'quizz:quiz_question' tutorial_id=quiz.id %}" class="w3-btn w3-margin-bottom w3-black w3-hover-amber">Try again</a>
</div>
{% endblock %}