C_Tut/C_Tut/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('accounts/',include('accounts.urls')),
    path('home/',include('home.urls')),
    path('tutorials/',include('tutorials.urls')),
    path('quiz/',include('quizz.urls')),
    path('contact/',include('contact.urls')),
    path('admin/', admin.site.urls),
]

C_Tut/accounts/urls.py
from django.urls import path
from . import views


app_name='accounts'
urlpatterns=[
    path('', views.index , name='index'),
    path( 'login/' , views.loginUser.as_view() , name='login'),
    path('signup',views.signupUser.as_view(),name='signup'),
    path('logout',views.logout_user.as_view(),name='logout'),
]

C_Tut/home/urls.py
from django.urls import path
from . import views


app_name='home'
urlpatterns=[
    path('',views.index,name='index'),
    path('about',views.about,name="about"),
    path('team',views.team,name="team"),
]

C_Tut/accounts/models.py
from django.db import models

# Create your models here.

C_Tut/accounts/forms.py
from django import forms
from django.contrib.auth.models import User
from home.models import student

class registerUserForm(forms.Form):
    username=forms.CharField(max_length=50)
    password=forms.CharField(max_length=32,widget=forms.PasswordInput)
    passwordAgain=forms.CharField(max_length=32,widget=forms.PasswordInput)
    first_name=forms.CharField(max_length=30)
    last_name=forms.CharField(max_length=30)
    email=forms.EmailField(max_length=256)
    class Meta:
        model=User
        fields=('username','password','first_name','last_name','email')
    
class studentRegisterForm(registerUserForm):
    collage_name=forms.CharField(max_length=256)
    class Meta:
        model=student
        fields=('username','password','first_name','last_name','email','collage_name')

C_Tut/accounts/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse, HttpResponseRedirect
from django.views import View
from django.contrib.auth.models import User
from django.contrib.auth import authenticate,login,logout
from django.views.decorators.cache import never_cache
from django.contrib.auth.hashers import make_password
from home.models import CPerson , student
from . import forms

from django.core.mail import send_mail
from django.conf import settings
# Create your views here.
def index(request):
    return HttpResponse('You\'re on accounts page' )

class signupUser(View):
    temp_name='accounts/signup.html'
    message=""
    def get(self,request):
        form=forms.studentRegisterForm()
        return render(request,self.temp_name,{'form':form})
    def post(self,request):
        form=forms.studentRegisterForm(request.POST)
        if form.is_valid() and form.cleaned_data['password']==form.cleaned_data['passwordAgain']:
            username=form.cleaned_data['username']
            err=False;
            try:
                user=User.objects.get(username=username)
                message="Username Exists!! Try another"
                form=forms.studentRegisterForm()
                return render(request,'accounts/signup.html',{'message':message,'form':form,})
            except:
                first_name=form.cleaned_data['first_name']
                last_name=form.cleaned_data['last_name']
                email=form.cleaned_data['email'] 
                collage_name=form.cleaned_data['collage_name']
                password=form.cleaned_data['password']
                password=make_password(password,salt=None,hasher='default')
                user=User(username=username,password=password,first_name=first_name,last_name=last_name,email=email)
                user.save()
                person=CPerson(user=user)
                person.save()
                stu=student(cperson=person,collage_name=collage_name)
                stu.save()
                wel_message='Hi'+first_name+last_name+'.'+'Welcome to JDPTUTS.Let us learn for a better future' 
                send_mail('Welcome',
                         wel_message,
                         settings.EMAIL_HOST_USER,
                         [email],
                         fail_silently=False)
                login(request,user)
                return redirect('tutorials:stu_home')
        else:
            message="Check whether password and confirm password field are same or not"
            form=forms.studentRegisterForm()
            return render(request,'accounts/signup.html',{'message':message,'form':form,})   
                
#@never_cache
class loginUser(View):
    temp_name='accounts/login.html'
    @never_cache
    def get(self,request):
        if request.user.is_authenticated==True:
            return redirect('tutorials:stu_home')
        else:
            return render(request,self.temp_name)
    @never_cache
    def post(self,request):
        username=request.POST.get('username')
        password=request.POST.get('password')
        user=authenticate(username=username,password=password)
        if user is not None:
            if user.is_active:
                login(request,user)
                return redirect('tutorials:stu_home')
        else:
            message="Please enter correct username and password"
            return render(request,self.temp_name,{'message':message,})
    
    
class logout_user(View):
    @never_cache
    def post(self,request):
        logout(request)
        return redirect('accounts:login')
    
    

C_Tut/accounts/templates/accounts/login.html
{% load widget_tweaks %}
{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'accounts/w3.css' %}">
<link rel="stylesheet" type="text/css" href="{% static 'accounts/loginstyle.css' %}">
<!--modal login
        <div id="modlogin" class="w3-modal" style="display: none">
    <div class="w3-modal-content w3-card-4 w3-animate-zoom" style="max-width:600px">
      
      <div class="w3-center" >
        <img src="{% static 'accounts/images/avatar.png' %}" alt="Avatar" style="width:30%" class="w3-circle w3-margin-top">
      </div>

      <form class="w3-container" action="#">
        <div class="w3-section">
          <label><b>Username</b></label>
          <input class="w3-input w3-border-bottom w3-margin-bottom" type="text" placeholder="Enter Username" name="username" required>
          <label><b>Password</b></label>
          <input class="w3-input w3-border-bottom" type="password" placeholder="Enter Password" name="pass" required>
            <input class="w3-check w3-margin-top" type="checkbox" checked="checked"> Remember me
          <button class="w3-button w3-block w3-black w3-hover-amber w3-section w3-padding" type="submit">Login</button>
        </div>
      </form>
        <div class="w3-container">
        <b>Not with Us?</b>
            <a href="{% url 'accounts:signup' %}" style="text-decoration: none">
                <button class="w3-button w3-block w3-black w3-hover-amber w3-section w3-padding">SignUp</button></a>
        </div>
      <div class="w3-container w3-border-top w3-padding-16 w3-light-grey">
        <span class="w3-right w3-padding"><a href="#">Forgot password?</a></span>
      </div>
    </div>
  </div>-->
{% if message %}
    <div id="mod-message" class="w3-modal">
    <div class="w3-modal-content">
      <header class="w3-container w3-black" style="z-index: 2;"> 
        <h2 class="w3-center">ERROR!!!</h2>
      </header>
      <div class="w3-container">
        <p class="w3-center">{{message}}</p>
      </div>
      <footer >
          <div class="w3-container w3-center w3-padding w3-light-grey w3-border-top">
          <button onclick="document.getElementById('mod-message').style.display='none'" 
        class="w3-center w3-button w3-black w3-padding">OK</button>
          </div>
      </footer>
    </div>
  </div>
{% endif %}

<div class="w3-container">
    <div class="w3-card-4 w3-display-middle" style="max-width: 600px;min-width: 320px">
        <div class="w3-center" >
        <img src="{% static 'accounts/images/avatar.png' %}" alt="Avatar" style="width:15%;" class="w3-circle w3-margin-top">
      </div>

      <form class="w3-container" action="{% url 'accounts:login' %}" method="post">
          {% csrf_token %}
        <div class="w3-section">
          <label><b>Username</b></label>
          <input class="w3-input w3-border-bottom w3-margin-bottom" type="text" placeholder="Enter Username" name="username" required>
          <label><b>Password</b></label>
          <input class="w3-input w3-border-bottom" type="password" placeholder="Enter Password" name="password" required>
            <input class="w3-check w3-margin-top" type="checkbox" checked="checked"> Remember me
          <button class="w3-button w3-block w3-black w3-hover-amber w3-section w3-padding" type="submit">Login</button>
        </div>
      </form>
        <div class="w3-container">
        <b>Not with Us?</b>
            <a href="{% url 'accounts:signup' %}" style="text-decoration: none">
                <button class="w3-button w3-block w3-black w3-hover-amber w3-section w3-padding">SignUp</button></a>
        </div>
      <div class="w3-container w3-border-top w3-padding-16 w3-light-grey">
        <span class="w3-right w3-padding"><a href="#">Forgot password?</a></span>
      </div>

    </div>
</div>

C_Tut/accounts/templates/accounts/signup.html
{% load widget_tweaks %}
{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'accounts/w3.css' %}">
<link rel="stylesheet" type="text/css" href="{% static 'accounts/loginstyle.css' %}">
<!--
<div id="modsignup" class="w3-modal" style="display: block">
    <div class="w3-modal-content w3-card-4 w3-animate-zoom" style="max-width:600px">
  
      <div class="w3-center"><br>
        <img src="{% static 'accounts/images/avatar.png' %}" alt="Avatar" style="width:30%" class="w3-circle w3-margin-top">
      </div>

      <form class="w3-container" action="#">
        <div class="w3-section">
          <label><b>Username</b></label>
          <input class="w3-input w3-border-bottom w3-margin-bottom" type="text" placeholder="Enter Username" name="username" required>
          <label><b>Password</b></label>
          <input class="w3-input w3-border-bottom w3-margin-bottom" type="password" placeholder="Enter Password" name="pass" required>
            <label><b>Confirm Password</b></label>
          <input class="w3-input w3-border-bottom" type="password" placeholder="Enter Password again" name="pass" required>
          <button class="w3-button w3-block w3-black w3-hover-amber w3-section w3-padding" type="submit">SignUp</button>
        </div>
      </form>
        <div class="w3-container">
        <b>Already have an Account?</b>
            <a href="{% url 'accounts:login' %}" style="text-decoration: none">
            <button class="w3-button w3-block w3-black w3-hover-amber w3-section w3-padding">LogIn</button>
        </a>
        </div>

      <div class="w3-container w3-border-top w3-padding-16 w3-light-grey">
      </div>
    </div>
  </div>-->
{% if message %}
    <div id="mod-message" class="w3-modal">
    <div class="w3-modal-content">
      <header class="w3-container w3-black"> 
        <h2 class="w3-center">ERROR!!!</h2>
      </header>
      <div class="w3-container">
        <p class="w3-center">{{message}}</p>
      </div>
      <footer class="w3-container w3-center w3-padding w3-light-grey w3-border-top">
          <button onclick="document.getElementById('mod-message').style.display='none'" 
        class="w3-center w3-button w3-black w3-padding">OK</button>
      </footer>
    </div>
  </div>
{% endif %}

<div class="w3-container">
<div class="w3-card-4 w3-display-middle" style="max-width: 600px;min-width: 320px">
    <div class="w3-center w3-margin-bottom"><br>
        <img src="{% static 'accounts/images/avatar.png' %}" alt="Avatar" style="width:15%;" class="w3-circle">
      </div>

      <form class="w3-container" action="{% url 'accounts:signup' %}" method="post">
          {% csrf_token %}
        <div class="w3-section">
            <div class="w3-row">
                <div class="w3-col l3 m4 w3-center w3-margin-top"><label><b>Username</b></label></div>
                <div class="w3-col l9 m8">{% render_field form.username class+="w3-input w3-border-bottom w3-margin-bottom" autocomplete="off" placeholder="Username" %}</div>
            </div>
            <div class="w3-row">
                <div class="w3-col l3 m4 w3-center w3-margin-top"><label><b>Email</b></label></div>
                <div class="w3-col l9 m8">{% render_field form.email class+="w3-input w3-border-bottom w3-margin-bottom" autocomplete="off" placeholder="Email" type='email' %}</div>
            </div>
            <div class="w3-row">
                <div class="w3-col l3 m4 w3-center w3-margin-top"><label><b>First&nbsp;Name</b></label></div>
                <div class="w3-col l9 m8">{% render_field form.first_name class+="w3-input w3-border-bottom w3-margin-bottom" autocomplete="off" placeholder="Enter your first name" %}</div>
            </div>
            <div class="w3-row">
                <div class="w3-col l3 m4 w3-center w3-margin-top"><label><b>Last&nbsp;Name</b></label></div>
                <div class="w3-col l9 m8">{% render_field form.last_name class+="w3-input w3-border-bottom w3-margin-bottom" autocomplete="off" placeholder="Enter your last name" %}</div>
            </div>
            <div class="w3-row">
                <div class="w3-col l3 m4 w3-center w3-margin-top"><label><b>Collage&nbsp;Name</b></label></div>
                <div class="w3-col l9 m8">{% render_field form.collage_name class+="w3-input w3-border-bottom w3-margin-bottom" autocomplete="off" placeholder="Your Collage name" %}</div>
            </div>
            <div class="w3-row">
                <div class="w3-col l3 m4 w3-center w3-margin-top"><label><b>Password</b></label></div>
                <div class="w3-col l9 m8"> {% render_field form.password class+="w3-input w3-border-bottom w3-margin-bottom" autocomplete="off" placeholder="Password" type="password" %}</div>
            </div>
            <div class="w3-row">
                <div class="w3-col l3 m4 w3-center w3-margin-top"><label><b>Confirm Password</b></label></div>
                <div class="w3-col l9 m8">{% render_field form.passwordAgain class+="w3-input w3-border-bottom w3-margin-top" autocomplete="off" placeholder="Password Again" type="password" %}</div>
            </div>
            <button class="w3-button w3-block w3-black w3-hover-amber w3-section w3-padding" type="submit">SignUp</button>
        </div>
      </form>
        <div class="w3-container">
        <b>Already have an Account?</b>
            <a href="{% url 'accounts:login' %}" style="text-decoration: none">
            <button class="w3-button w3-block w3-black w3-hover-amber w3-section w3-padding">LogIn</button>
        </a>
        </div>

      <div class="w3-container w3-border-top w3-padding-16 w3-light-grey">
      </div>
    </div>
</div>